// Downloads the receipts of Uber Eats orders
// from https://www.ubereats.com/orders
//
// Usage:
//   node uber.js <dir> from <YYYY-MM-DD> [to <YYYY-MM-DD>]
//
// Saves the receipts (as PDFs generated by Uber) of the orders
// placed in the date range which are not yet in <dir>
// as `<order date>_uber_eats.pdf`
// (`_2`, `_3`, … for further orders of the day, ordered by order time)
// and prints their paths to stdout.
// The receipt of an order which was tipped afterwards is the one
// including the tip ("Receipt Including Tip").
// Dates are the local dates of the orders as shown in the receipts.
//
// The login has to be completed manually in the browser.
// It's remembered in the browser profile "uber".

import path from "node:path"
import {pathToFileURL} from "node:url"

import fse from "fs-extra"

import {dumpDebugFiles, launchBrowser} from "../browser.js"

const log = console.warn
const eatsUrl = "https://www.ubereats.com"
const ordersUrl = `${eatsUrl}/orders`


// Calls an endpoint of the Uber Eats web app API
// (any "x-csrf-token" is accepted, but it must be set)
async function callEatsApi (page, endpoint, data) {
  const response = await page.request.post(`${eatsUrl}/_p/api/${endpoint}`, {
    headers: {"x-csrf-token": "x", "content-type": "application/json"},
    data,
  })
  const body = await response.json()
    .catch(() => null)
  if (body?.status !== "success") {
    throw new Error(`${endpoint} failed (HTTP ${response.status()})`)
  }
  return body.data
}


async function isLoggedInToEats (page) {
  try {
    await callEatsApi(page, "getPastOrdersV1", {lastWorkflowUUID: ""})
    return true
  }
  catch {
    return false
  }
}


export async function login (page) {
  log(`Open ${ordersUrl}`)
  await page.goto(ordersUrl, {timeout: 30000})
  if (await isLoggedInToEats(page)) {
    return
  }
  log("Please log in in the browser …")
  for (let waited = 0; waited < 600000; waited += 3000) {
    await page.waitForTimeout(3000)
    if (await isLoggedInToEats(page)) {
      return
    }
  }
  throw new Error("Login timed out")
}


const monthNumbers = {
  // English
  jan: 1, feb: 2, mar: 3, apr: 4, may: 5, jun: 6,
  jul: 7, aug: 8, sep: 9, oct: 10, nov: 11, dec: 12,
  // German
  januar: 1, februar: 2, märz: 3, mai: 5, juni: 6, juli: 7,
  okt: 10, oktober: 10, dez: 12, dezember: 12,
}


function toMonthNumber (monthName) {
  const name = monthName.toLowerCase()
    .replace(/\.$/, "")
  return monthNumbers[name] ?? monthNumbers[name.slice(0, 3)] ?? null
}


function formatDate (year, month, day) {
  return [year, month, day]
    .map(number => String(number)
      .padStart(2, "0"))
    .join("-")
}


// Returns the first date in the receipt text as "YYYY-MM-DD",
// e.g. of "Mar 19, 2026" or "30. Mai 2025"
export function getReceiptDate (text) {
  const english = text.match(/\b([A-Z][a-z]{2,8})\.? (\d{1,2}), (\d{4})\b/)
  const german = text.match(/\b(\d{1,2})\. ([A-ZÄ][a-zä]{2,8})\.? (\d{4})\b/)
  const candidates = [
    english && {
      index: english.index,
      month: toMonthNumber(english[1]),
      day: english[2],
      year: english[3],
    },
    german && {
      index: german.index,
      month: toMonthNumber(german[2]),
      day: german[1],
      year: german[3],
    },
  ]
    .filter(candidate => candidate?.month)
    .sort((first, second) => first.index - second.index)
  const date = candidates[0]
  return date ? formatDate(date.year, date.month, date.day) : null
}


function htmlToText (html) {
  return html
    .replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/g, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;|&#160;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
}


// Returns `[{uuid, store, createdAt, completedAt, total, currency}]`
// of all past Uber Eats orders
export async function getEatsOrders (page) {
  const orders = []
  let cursor = ""
  do {
    const data = await callEatsApi(page, "getPastOrdersV1",
      {lastWorkflowUUID: cursor})
    for (const uuid of data.orderUuids) {
      const {baseEaterOrder, storeInfo, fareInfo} = data.ordersMap[uuid]
      const created = baseEaterOrder.orderStateChanges
        ?.find(change => change.type === "CREATED")
      orders.push({
        uuid,
        store: storeInfo?.title,
        createdAt: created?.stateChangeTime ?? baseEaterOrder.completedAt,
        completedAt: baseEaterOrder.completedAt,
        isCancelled: baseEaterOrder.isCancelled,
        total: fareInfo?.totalPrice / 100,
        currency: baseEaterOrder.currencyCode,
      })
    }
    const nextCursor = data.paginationData?.nextCursor
    cursor = data.meta?.hasMore && nextCursor && nextCursor !== cursor
      ? nextCursor
      : ""
  } while (cursor)
  return orders
}


// Returns the latest receipt of the order (`timestamp` selects
// an older one of `receiptsForJob`, e.g. the one before the tip)
// as `{date, text, receiptsForJob}` (contentType "WEB_HTML")
// or as `{pdf}` (contentType "PDF")
export async function getEatsReceipt (
  page,
  uuid,
  {contentType = "WEB_HTML", timestamp = null} = {},
) {
  const data = await callEatsApi(page, "getReceiptByWorkflowUuidV1",
    {contentType, workflowUuid: uuid, timestamp})
  if (contentType === "PDF") {
    const pdf = Buffer.from(data.receiptData, "base64")
    if (!pdf.subarray(0, 5)
      .toString()
      .startsWith("%PDF")) {
      throw new Error(`Receipt of order ${uuid} is not a PDF`)
    }
    return {pdf, receiptsForJob: data.receiptsForJob}
  }
  const text = htmlToText(data.receiptData)
  return {
    date: getReceiptDate(text),
    text,
    receiptsForJob: data.receiptsForJob,
  }
}


function addDays (isoDate, days) {
  const date = new Date(`${isoDate}T00:00:00Z`)
  date.setUTCDate(date.getUTCDate() + days)
  return date.toISOString()
    .slice(0, 10)
}


// Appends `_2`, `_3`, … to the names of further documents of a day.
// `documents` must be sorted by time.
export function addFileNames (documents, label) {
  const countPerDate = {}
  return documents.map(document => {
    countPerDate[document.date] = (countPerDate[document.date] ?? 0) + 1
    const counter = countPerDate[document.date]
    const suffix = counter > 1 ? `_${counter}` : ""
    return {...document, fileName: `${document.date}_${label}${suffix}.pdf`}
  })
}


// Returns the orders whose receipts are dated in the range
// with their `date` and `fileName`
export async function getEatsReceiptsInRange (page, {from, to}) {
  const orders = (await getEatsOrders(page))
    .filter(order => !order.isCancelled)
    // The local date can differ by a day from the UTC date
    .filter(order => {
      const utcDate = order.createdAt.slice(0, 10)
      return utcDate >= addDays(from, -1) && (!to || utcDate <= addDays(to, 1))
    })
    .sort((first, second) =>
      first.createdAt.localeCompare(second.createdAt))

  const datedOrders = []
  for (const order of orders) {
    const {date} = await getEatsReceipt(page, order.uuid)
    datedOrders.push({...order, date: date ?? order.createdAt.slice(0, 10)})
  }
  // Number the receipts of a day from the first order of the day,
  // independent of the requested range
  return addFileNames(datedOrders, "uber_eats")
    .filter(order => order.date >= from && (!to || order.date <= to))
}


export async function downloadEatsReceipts (page, {outputDir, from, to}) {
  const orders = await getEatsReceiptsInRange(page, {from, to})
  log(`Found ${orders.length} Uber Eats orders`)
  const savedPaths = []
  for (const order of orders) {
    const filePath = path.join(outputDir, order.fileName)
    const description = `${order.date} ${order.store} ` +
      `(${order.total} ${order.currency})`
    if (await fse.pathExists(filePath)) {
      log(`Skip ${description} (already downloaded)`)
      continue
    }
    const {pdf} = await getEatsReceipt(page, order.uuid,
      {contentType: "PDF"})
    await fse.writeFile(filePath, pdf)
    log(`Saved ${description}`)
    savedPaths.push(filePath)
  }
  return savedPaths
}


function parseArgs (args) {
  const options = {}
  for (let index = 0; index < args.length; index += 2) {
    const [key, value] = [args[index], args[index + 1]]
    if (!["from", "to"].includes(key) || !/^\d{4}-\d{2}-\d{2}$/.test(value)) {
      return null
    }
    options[key] = value
  }
  return options.from ? options : null
}


async function main () {
  const [outputDir, ...args] = process.argv.slice(2)
  const options = parseArgs(args)
  if (!outputDir || !options) {
    console.error(
      "Usage: node uber.js <dir> from <YYYY-MM-DD> [to <YYYY-MM-DD>]")
    process.exitCode = 1
    return
  }

  const {browser, page} = await launchBrowser({
    shallShowBrowser: true,
    persistentProfileName: "uber",
    acceptDownloads: false,
  })

  try {
    await login(page)
    await fse.ensureDir(outputDir)
    const savedPaths = await downloadEatsReceipts(page,
      {outputDir, ...options})
    savedPaths.forEach(filePath => console.info(filePath))
    log(`Downloaded ${savedPaths.length} new receipts`)
  }
  catch (error) {
    await dumpDebugFiles(page, "uber-debug")
    console.error(error)
    process.exitCode = 1
  }
  finally {
    await browser.close()
  }
}


// Allows importing the functions, e.g. to test them in a running browser
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main()
}
