name: Run tests and deploy webapp to GitHub Pages

on:
  push:
    branches: ["master"]

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Install Cargo
        uses: dtolnay/rust-toolchain@stable

      - name: Install Nickel
        run: cargo install nickel-lang-cli

      - name: Build project and run tests
        run: make test

      - name: Build docs
        run: make docs

      - name: Upload artifact
        if: runner.os == 'Linux'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        if: runner.os == 'Linux'
        id: deployment
        uses: actions/deploy-pages@v4
